<a href="https://colab.research.google.com/github/heejininku/Class2022Spring/blob/main/2022S20_tensorflow_hub(5.30%201st_%EA%B0%95%EC%9D%98%EC%A0%95%EB%A6%AC).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### [Tensorflow Hub](https://www.tensorflow.org/hub)

### image classification (e.g. [inception_v3](https://tfhub.dev/google/imagenet/inception_v3/classification/5))

In [ ]:
import tensorflow.compat.v2 as tf
import tensorflow_hub as hub

In [ ]:
model = hub.KerasLayer("https://tfhub.dev/google/imagenet/inception_v3/classification/5") 
#이 모델이 함수같이 쓰이는 것.

In [ ]:
from PIL import Image #이미지 관련 라이브러리
import requests
url = 'http://images.cocodataset.org/val2017/000000039769.jpg' 
#고양이 그림을  url로 지정해서 이미지로 받아오는것.
image = Image.open(requests.get(url, stream=True).raw)

In [ ]:
import numpy as np 
#numpy 형태로 array화 해주어야 함.
image = np.array(image) #이제 image 드래그 해보면 숫자가 나옴. (맨 끝이 3- 컬러니까)

In [ ]:
image[:,:,0]

array([[[0.54901963, 0.09803922, 0.21960786],
        [0.5411765 , 0.08627451, 0.22352943],
        [0.5294118 , 0.08627451, 0.16470589],
        ...,
        [0.9294118 , 0.3921569 , 0.74509805],
        [0.90196085, 0.32941177, 0.86666673],
        [0.9333334 , 0.3921569 , 0.6862745 ]]], dtype=float32)

In [ ]:
# reshape into shape [batch_size(사진 개수를 쓴다고 생각하면 됨), height, width, num_channels]
image = tf.reshape(image, [1, image.shape[0], image.shape[1], image.shape[2]]) 
#reshape해야 함.- 3차원의 array를 4차원으로 바꾸어주기(이 모델이 그것을 원함)

In [ ]:
# Use `convert_image_dtype` to convert to floats in the [0,1] range. 
#모델 자체는 0~1 사이로 (어두우면 0, 밝은 색이면 1로 이렇게)
image = tf.image.convert_image_dtype(image, tf.float32)

In [ ]:
image[0,:,:,0] #숫자가 0과 1 사이로 정리가 됨.

<tf.Tensor: shape=(480, 640), dtype=float32, numpy=
array([[0.54901963, 0.5647059 , 0.57254905, ..., 0.36862746, 0.41960788,
        0.40000004],
       [0.5411765 , 0.5568628 , 0.54509807, ..., 0.4039216 , 0.45098042,
        0.37647063],
       [0.5294118 , 0.5882353 , 0.5568628 , ..., 0.4039216 , 0.42352945,
        0.3647059 ],
       ...,
       [0.9294118 , 0.882353  , 0.92549026, ..., 0.67058825, 0.70980394,
        0.5764706 ],
       [0.90196085, 0.8862746 , 0.9333334 , ..., 0.44705886, 0.4039216 ,
        0.34901962],
       [0.9333334 , 0.96470594, 0.9333334 , ..., 0.2901961 , 0.2901961 ,
        0.28627452]], dtype=float32)>

In [ ]:
logits = model(image) #그들이 사용한 label이 1000개가 되는 것
logits 

<tf.Tensor: shape=(1, 1001), dtype=float32, numpy=
array([[ 0.13278216, -0.98323435,  0.4061772 , ..., -0.12934873,
         0.38595918,  0.4459334 ]], dtype=float32)>

In [ ]:
np.argmax(logits) #천개의 logits 중에서 뭐가 가장 높은 값이냐?를 알려주는 함수
#282번째꺼가 가장 확률이 높더라~

282

> https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt

교수님이 이 위에 사이트 들어가서 카피해서 엑셀에 넣어서282번째 것이 tabby라는 것을 알아차림.


tabby는 고양이_제대로 고양이를 파악해 냄.